%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
odom: 1
imu: 1         
num_of_cam: 1  

imu_topic: "/mynteye/imu/data_raw"
image0_topic: "/mynteye/left/image_mono"
odom_topic: "/odom"
output_path: "/home/xgs/init_ws/src/MYNT-EYE-VINS-FUSION-Samples-master/output/"

#cam0_calib: "left_equ.yaml"
cam0_calib: "left_pinhole.yaml"
#cam0_calib: "left_mei.yaml"
image_width: 640 
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Have no prior about extrinsic param, calibrate extrinsic param
estimate_extrinsic_io: 1 # 0 Have an accurate extrinsix parameters.
                         # 1 Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                         # 2  Have no prior about extrinsic param, calibrate extrinsic param
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99976584, 0.0110871,
       -0.01858353, 0.00090107,
       0.01078386, -0.99980835,
       -0.01633908, -0.00084974,
       -0.01876112, 0.01613485,
       -0.9996938, -0.00113472, 0., 0., 0., 1. ]

body_T_odom: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
#   data: [ 0.0, -1.0, 0.0, 0.0,
#           0.0, 0.0, 1.0, 0.0,
#           -1.0, 0.0, 0.0, 0.0, 
#           0., 0., 0., 1. ]

   data: [ 0.0, -1.0, 0.0, -0.06,
           0.0, 0.0, 1.0, 0.0,
           -1.0, 0.0, 0.0, 0.12, 
           0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.08 #0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 16 #8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.0331633080376         # accelerometer measurement noise standard deviation. #0.599298904976
gyr_n: 0.00224577113705        # gyroscope measurement noise standard deviation.     #0.198614898699
acc_w: 0.0003871         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0000300      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.79746009     # gravity magnitude

#acc_n: 0.0268014618074          # accelerometer measurement noise standard deviation. #0.599298904976
#gyr_n: 0.00888232829671        # gyroscope measurement noise standard deviation.     #0.198614898699
#acc_w: 0.00262960861593         # accelerometer bias random work noise standard deviation.  #0.02
#gyr_w: 0.000379565782927       # gyroscope bias random work noise standard deviation.     #4.0e-5
#
#g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/xgs/init_ws/src/MYNT-EYE-VINS-FUSION-Samples-master/output/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
